### ISSUE TITLE
[LLVM::CLANG] Build with warning, unknown runtime behaviour 

### ISSUE THREAD

**Issue by DaVieS007** [matusnovak/simplesquirrel#4]
warning: multiple unsequenced modifications to 'index' [-Wunsequenced]                     push(vm, std::forward<R>(funcPtr->ptr->operator()(pop<typename std::remove_reference<Args>::type>(vm, index--)...)));

Seems like Clang can't support decrementing values in variadic template's arguments.

**Comment by matusnovak** [comment]
Hi @DaVieS007 

I am currently occupied with work, I will have a closer look at this issue in few days from now.

**Comment by matusnovak** [comment]
@DaVieS007 Check the latest master. The warning has been fixed. Tests in Travis CI for OSX Clang should serve as a verification that the unknown runtime behaviour has been eliminated.

**Comment by DaVieS007** [comment]
@matusnovak Excellent work, I'll test on FreeBSD's CLANG tonight and OSX next week.

**Comment by DaVieS007** [comment]
@matusnovak Im here to leave that message, CLANG compiles fine, compiled binary working as expected.
Thank you.

**Comment by matusnovak** [comment]
@DaVieS007 Glad to hear that! Feel free to post any other issues you have. More than happy to help.
